### ISSUE TITLE
 Mock File Operations in `add_or_update_normal_file`

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#11] opened 2024-10-01 16:18 UTC
- **Description**: Mock file operations (like file access) in the `add_or_update_normal_file` tests to simulate various file system behaviors, including files that exist and files that do not. This ensures the function behaves as expected without relying on the actual file system.
   - **Resources**: Refer to the [pytest mocking section](https://docs.pytest.org/en/stable/getting-started.html) for instructions on mocking file access operations.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by SandyK1002** [comment] 2024-10-01 17:58
Can I work on this issue?

**Comment by Kota-Karthik** [comment] 2024-10-01 18:07
@SandyK1002 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by KartikSaxena19** [comment] 2024-10-08 10:49
You can assign this task to me

**Comment by techy4shri** [comment] 2024-10-08 10:58
@KartikSaxena19 let's wait for tonight, if Sandeep  does not respond, you will be assigned to this issue.

**Comment by KartikSaxena19** [comment] 2024-10-08 15:19
I will try my best to resolve this issue within 1 or 2 days if I complete this issue in the given time period than please assign compare and replace issue to me

**Comment by JahnaviDhanaSri** [comment] 2024-10-09 18:05
Hello can you please assign this issue to me

**Comment by techy4shri** [comment] 2024-10-09 18:38
@JahnaviDhanaSri This is the 3rd time I am seeing you commenting on an assigned issue which also has a recently made PR.
This is your forst warning, either raise issues on your own or you won't be assigned unless the issue is currently not assigned to someone else.

**Comment by JahnaviDhanaSri** [comment] 2024-10-10 00:25
Ok

**Comment by ShirshenduR** [comment] 2024-10-11 17:54
assign me this issue

**Comment by Kota-Karthik** [comment] 2024-10-14 17:45
@JahnaviDhanaSri 
Do you still want to work on this issue?

**Comment by Jasmeetkaur-13** [comment] 2024-10-15 09:40
Could you please assign me to the task of writing unit tests for the setMinFileSize method? I'm ready to begin implementing the tests according to the guidelines.

**Comment by lakshyaog** [comment] 2024-10-16 14:01
@Kota-Karthik you can assign this task to me  i can help .

**Comment by Kota-Karthik** [comment] 2024-10-17 11:22
@lakshyaog 
make sure to create a separate branch before making the necessary changes and retain the folder structure
strictly follow PR template before raising any PR.

**Comment by lakshyaog** [comment] 2024-10-17 11:24
Okk thank u

**Comment by Kota-Karthik** [comment] 2024-10-26 09:21
@lakshyaog 
any updates ?
are you working on this ?
reply by EOD , else i will be unassigning you !

**Comment by lakshyaog** [comment] 2024-10-26 09:23
Sorry to say but u can assign to anyother thank u for your assign

**Comment by yashksaini-coder** [comment] 2024-10-26 11:06
I want to work on this issue @Kota-Karthik

**Comment by ShirshenduR** [comment] 2024-10-26 16:05
> This issue is now open to all. Whoever replies to me first will be assigned.

Assign me

**Comment by techy4shri** [comment] 2024-10-26 16:07
@ShirshenduR you are assigned.

**Closed** 2024-10-28 07:16 UTC
Labels: good first issue, level2, intermediate, gssoc-ext, hacktoberfest, hacktoberfest-accepted, up-for-grabs
